eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://peer1:8000/eureka/
server:
  #当前服务端口号
  port: 8768
spring:
  application:
    #当前应用名称
    name: config
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/453055141/spring-cloud.git
          search-paths: spring-cloud-config
          username: 453055141
          password: lvmm1992111
      label: master
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zengkai
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        allowed-methods: "*"