eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://peer1:8000/eureka/
server:
  #当前服务端口号
  port: 8764
spring:
  application:
    #当前应用名称
    name: sms
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq: rabbitmq
              addresses: rabbitmq-server
              username: zengkai
              password: 123456
              virtual-host: /
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: testTopic # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
  datasource:
    master:
      username: zengkai
      password: 1992111
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://119.23.106.184:3306/zk_project?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
      type: com.alibaba.druid.pool.xa.DruidXADataSource
      initial-size: 1
      min-idle: 3
      max-wait: 600
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true

    slave:
      one:
        max-active: 20
        username: zengkai
        password: 1992111
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://119.23.106.184:3306/zk_project_two?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        type: com.alibaba.druid.pool.xa.DruidXADataSource
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
      two:
        max-active: 20
        username: zengkai
        password: 1992111
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://119.23.106.184:3306/sks_star??useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        type: com.alibaba.druid.pool.xa.DruidXADataSource
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
#启用断路器
feige:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.service