#server:
#  port: 8080
#
##spring
#spring:
#  #启用自动重启
#  devtools:
#    restart:
#      enabled: true
#
#  # H2 DATABASE CONFIG
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://119.23.106.184:3306/zk_project?useUnicode=true&characterEncoding=utf8
#    username: zengkai
#    password: 1992111
#    druid:
#      url: jdbc:mysql://119.23.106.184:3306/zk_project?useUnicode=true&characterEncoding=utf8
#      username: zengkai
#      password: 1992111
#      initial-size: 10
#      min-idle: 5
#      max-active: 50
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: false
#      test-on-return: false
#      test-on-borrow: false
#      filters: stat,wall,slf4j,config
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      #webstat
#      web-stat-filter:
#        enabled: true
#        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
#      filter:
#        slf4j:
#          enabled: true
#          connection-log-enabled: true
#          connection-close-after-log-enabled: true
#          connection-commit-after-log-enabled: true
#          connection-connect-after-log-enabled: true
#          connection-connect-before-log-enabled: true
#          connection-log-error-enabled: true
#          data-source-log-enabled: true
#          result-set-log-enabled: true
#          statement-log-enabled: true
#
#
##mybatis
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.baomidou.springboot.entity
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
#  global-config:
#    # 数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: id_worker
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
##      db-type: h2
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false