eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
  port: 8771
spring:
  application:
    #当前应用名称
    name: elasticsearch
  data:
    #ElasticSearch的连接地址
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 119.23.106.184:9300
      repositories:
        enabled: true